### PR TITLE
Fat Contracts Tutorial

### PR DESCRIPTION
**Pull request by HashWarlock**
# Target
- [x] Port over the existing Fat Contracts Workshop to the Developer Wiki
- [ ] Rebase after merge of PR #49
- [ ] Re-order steps for the tutorial where needed
- [ ] Add links & references to Fat Contracts related wiki content

# Procedure

- Port `README.md` file from the `fat-contracts-workshop` repo
- Re-order steps & fix description of steps that need to be updated
- Add links & references to wiki pages specific to Fat Contracts
- Add some updates to the playing with the Flipper contract

### CODE REVIEW

**Comment by hauni97** [comment]
@HashWarlock I am unsure if you have seen this PR: https://github.com/Phala-Network/phala-wiki-next/pull/49
There is a new structure and the content you added is here since 8 days: https://github.com/Phala-Network/phala-wiki-next/commit/435e15844fc69aca2e2bf9b6168cba83979cfb3a
Check the preview here: https://deploy-preview-49--phala-wiki-preview.netlify.app/en-us/build/developer/fat-contract-examples/

**Comment by hauni97** [comment]
> 

This commit https://github.com/Phala-Network/phala-wiki-next/commit/435e15844fc69aca2e2bf9b6168cba83979cfb3a followed the procedure you applied, of porting over the existing Fat Contracts Workshop to the Developer Wiki. If you wish, you can audit it according to the remaining targets:

> * [ ] Re-order steps for the tutorial where needed
> * [ ] Add links & references to Fat Contracts related wiki content

**Comment by HashWarlock** [comment]
This PR will be rebased on PR #49 to update existing fat contracts example wiki page from [435e158](https://github.com/Phala-Network/phala-wiki-next/commit/435e15844fc69aca2e2bf9b6168cba83979cfb3a).

**Comment by HashWarlock** [comment]
Going to close this PR in favor of PR #65

**Pull request closed without merging**
